### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by elijahcruz12** [Mte90/WP-Mozilla#11]
For the theme, maybe add a plugin to include widgets that would work well for users of this?

**Comment by Mte90** [comment]
Can you explain better?
A theme can have widget if necessary but they are supported from other plugin in this theme.

**Comment by elijahcruz12** [comment]
Well I don't have total WP experience with coding it, but I notice somethings that can be changed on the theme to make it look like mozilla sites.

**Comment by elijahcruz12** [comment]
I was just saying you should also do widgets for this.

**Comment by Mte90** [comment]
I don't understand what is the purpose of the issue

**Comment by elijahcruz12** [comment]
I don't know I lost my thought earlier.
