### ISSUE TITLE
request design resources for mozilla clubs

### ISSUE THREAD

**Issue by ghost** [Mte90/WP-Mozilla#12]
Hi my name is steve, and am currently helping build the mozilla club repo.  I was wondering if you wouldn't mind contributing some of your templates to the repo? 

It would be nice for club captains or prospective ones to be able to find these on the clubs repo. 

~Steve

**Comment by Mte90** [comment]
I am keeping that resources on https://wiki.mozilla.org/Webdev/GetInvolved/WordPress

Actually my themes are incomplete or outdated and I have no time to continue on work on it. Also the design is changed again so they are very obsolete right now :-/
